apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-2
  namespace: humor-game
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 2Gi
